/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Role Handlers
 #	author : miyako
 #	2015/09/25
 #
 # --------------------------------------------------------------------------------*/



// --- Role Handlers
void Get_default_application(sLONG_PTR *pResult, PackagePtr pParams);
void Set_default_application(sLONG_PTR *pResult, PackagePtr pParams);
void Get_capable_applications(sLONG_PTR *pResult, PackagePtr pParams);
